[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Dhayanithi Subramanian <dhayanithi@gmail.com>"]

[dependencies]
hex = "0.3.2"
base64 = "0.9.2"
lazy_static = "0.2.8"
openssl = "0.10.11"
rand = "0.5.5"


